### ISSUE TITLE
log in server console is missing spaces

### ISSUE THREAD

**Issue by pahanakun** [yitzy299/Ore-Readout#6]
the block broken log in server console is missing spaces eg [20:38:33] [Server thread/INFO]: pahanakunbrokeat7-63-9

its especially hard to tell the coordinates if y or z are positive, as its just a string of numbers with no spaces.

its fine in op chat, but I want that disabled, I just want it in my server console.

**Comment by yitzy299** [comment]
This is fixed if you compile yourself
